# Generated by Django 5.0.1 on 2024-01-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_heading', models.CharField(max_length=200)),
                ('about_details', models.TextField()),
                ('cv', models.FileField(upload_to='cv_pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('discord', models.CharField(blank=True, max_length=50, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.PositiveIntegerField()),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.PositiveIntegerField()),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='achievement_icons/')),
                ('details', models.TextField()),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='story_images/')),
                ('details', models.TextField()),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personaldetails')),
            ],
        ),
    ]
