# Generated by Django 5.0.1 on 2024-01-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='cv',
            field=models.FileField(upload_to='media/cv_pdfs/'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/'),
        ),
    ]
