# Generated by Django 5.0.1 on 2024-01-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_achievement_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
